# Generated by Django 4.2.16 on 2024-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product_images/default_product_image.jpg",
                upload_to="product_images/",
            ),
            preserve_default=False,
        ),
    ]
